debug: true
server:
  port: 3000
  servlet:
    context-path: /api
spring:
  config:
    import: secrets.yml
  application:
    name: hackweek-backend
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      platform: postgresql
      mode: always
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR


