spring:
  datasource:
    url: jdbc:sqlserver://databasehackweek.database.windows.net:1433;database=saltdb;user=nelsonJanusson@databasehackweek;password=5?6#cZ^">XTpWL>;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;


